id: A9BF94DD5
base_file: f8EA8.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:26:09.868318
  last_modified_at: 2022-06-11 13:26:09.868321
