id: A9BF94DD5
base_file: fB9CA.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:26:09.877585
  last_modified_at: 2022-06-11 13:26:09.877588
