id: A9BF94DD5
base_file: fCC6E.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:26:09.880576
  last_modified_at: 2022-06-11 13:26:09.880579
