id: A9BF94DD5
base_file: f72CC.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:26:09.854739
  last_modified_at: 2022-06-11 13:26:09.854742
