id: A9BF94DD5
base_file: f0C51.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:26:09.809935
  last_modified_at: 2022-06-11 13:26:09.809943
