id: A9BF94DD5
base_file: f722C.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:26:09.853200
  last_modified_at: 2022-06-11 13:26:09.853203
