id: A9BF94DD5
base_file: f4303.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:26:09.842546
  last_modified_at: 2022-06-11 13:26:09.842552
