id: A9BF94DD5
base_file: f93E7.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:26:09.871853
  last_modified_at: 2022-06-11 13:26:09.871857
